name: movie_flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.3+2
  google_sign_in: ^3.2.4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player: ^0.8.0

flutter:
  uses-material-design: true
  assets:
   - assets/1.mp4