version: "3"

services:
    container_rtmp:
        image: rtmp
        container_name: rtmp
        build:
            context: rtmp
            dockerfile: Dockerfile
        ports:
            - "1935:1935"
            - "9090:9090"

    container_node:
        image: node
        container_name: node
        build:
            context: node
            dockerfile: Dockerfile
        volumes:
            - ../movie_flutter_server:/app
        ports:
            - "8080:3000"
        tty: true
        command: [sh, -c, npm install && npm start]
